version: '3.9'

services:

  grpc-admin:
    build: .
    restart: always
    ports:
      - 50052:50052

  db:
    image: postgres:15.2-alpine3.17
    container_name: db
    environment:
      POSTGRES_PASSWORD: grpc-admin
      POSTGRES_USER: grpc-admin
      POSTGRES_DB: grpc-admin

    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grpc-admin"]
      interval: 3s
      timeout: 5s
      retries: 5
      
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411 

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.62.1
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./docker-compose-files/otel/otel-collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
    depends_on:
      - zipkin

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./docker-compose-files/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
      
  grafana:
    container_name: collector.grafana
    image: grafana/grafana:9.1.7
    ports:
      - "3000:3000"
    volumes:
      - ./docker-compose-files/prometheus/prometheus_ds.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml
    depends_on:
      - prometheus